### ISSUE TITLE
Metrics forwarder

### ISSUE THREAD

**Issue by tgross** [autopilotpattern/prometheus#13]
[ContainerMonitor](https://github.com/joyent/rfd/blob/master/rfd/0027/README.md) supports the Prometheus API but its clear, particularly given the poor story around long-term persistence (ref https://github.com/autopilotpattern/prometheus/issues/12), that we want to have a blueprint for metrics forwarding using the Prometheus API. This metrics forwarder would scrape Prometheus endpoints and then forward to an end-user's existing metrics collectors (ex. graphite, ES, nagios, etc.).

Open questions for this issue:
- what metrics collector(s) should we support? 
- what existing tooling is there for scraping Prometheus and forwarding the metrics? [telegraf](https://github.com/influxdata/telegraf) seems promising.
- should this be a separate blueprint or keep it in this repo as an alternative option?

_Edit_ see also https://github.com/misterbisson/telegraf/tree/wip

**Comment by misterbisson** [comment]
https://github.com/influxdata/telegraf is designed specifically for this purpose. It supports a number of [inputs](https://github.com/influxdata/telegraf/tree/master/plugins/inputs), including [prometheus](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus) and generic [json](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/httpjson), as well as a number of [outputs](https://github.com/influxdata/telegraf/tree/master/plugins/outputs).

I created https://github.com/misterbisson/telegraf/tree/wip to start work on this, please watch tickets in that repo to define it.

**Comment by misterbisson** [comment]
Closing this in favor of https://github.com/autopilotpattern/telegraf/issues/1 and https://github.com/autopilotpattern/telegraf/issues/2
