### ISSUE TITLE
docker-compose.yml environment missing

### ISSUE THREAD

**Issue by Smithx10** [autopilotpattern/prometheus#23]
Looks like,

 47     environment:
 48       - CONSUL=pc.svc.${TRITON_CNS_SEARCH_DOMAIN_PRIVATE}

Is missing from the consul definition.  When I ran `triton-compose scale consul=3 ` Consul couldn't find its cluster members.

**Comment by misterbisson** [comment]
These are set in [`triton-docker` and `triton-compose`](https://github.com/joyent/triton-docker-cli/blob/master/triton-docker#L91-L122), but the docs here don't reflect that, and the script requires local `docker`.

Given that, I'm closing this in favor of https://github.com/autopilotpattern/prometheus/issues/26
