### ISSUE TITLE
Automatically discover endpoints via discovery service

### ISSUE THREAD

**Issue by tgross** [autopilotpattern/prometheus#5]
In our [prometheus config](https://github.com/autopilotpattern/prometheus/blob/6e063d1f96ea7dcc46c155113a9adcce9bc61847/etc/prometheus.yml.ctmpl#L30-L33) we're using a list of service targets (and, incidentally, the wrong service!). But Prometheus supports using the service catalog directly via the [`<consul_sd_config>`](https://prometheus.io/docs/operating/configuration/#<consul_sd_config). This effectively makes it "autopilot pattern native", and we can just use that and eliminate the need to have `backend` handlers entirely.

**Comment by jacobloveless** [comment]
@tgross This definitely seems the better route: and really makes this dead simple.
I _think_ we just need to modify the relabel to NOT use every service in the catalog, but rather only target each instance once at the 'telemetry' port. Or alternatively we can just try to fudge the relabel to overwrite the port with <instance>:9090 ?
e.g. the default

> scrape_configs:
> - job_name: 'overwritten-default'
>   consul_sd_configs:
>   - server:   'localhost:8500'
>     services: ['consul', 'serviceA', 'serviceB']
>     relabel_configs:
>     source_labels: ['__meta_consul_service']
>     regex:         '(._)'
>     target_label:  'job'
>     replacement:   '$1'
>     source_labels: ['__meta_consul_node']
>     regex:         '(._)'
>     target_label:  'instance'
>     replacement:   '$1'
>     source_labels: ['__meta_consul_tags']
>     regex:         ',(production|canary|dev),'
>     target_label:  'group'
>     replacement:   '$1'

Will try to scrape EVERY service on each serice port at /metrics :0
I think it's something like ...

> ```
>   relabel_configs:
>   - source_labels: ['__meta_consul_node']
>     regex:         '.+(?<=:)'
>     target_label:  '__address__'
>     replacement:   '${1}9000'  
> ```

**Comment by jacobloveless** [comment]
Below is an example working config:

```

scrape_configs:
- job_name: 'overwritten-default'

  consul_sd_configs:
  - server:   'localhost:8500'
    services: ['consul', 'tickerplant', 'api-gateway', 'signode', 'portal']

  relabel_configs:
  - source_labels: [__meta_consul_service_address]
    target_label:  __address__
    replacement:   '${1}:9090'
  - source_labels: ['__meta_consul_service']
    regex:         '(.*)'
    target_label:  'job'
    replacement:   '$1'
  - source_labels: ['__meta_consul_node']
    regex:         '(.*)'
    target_label:  'instance'
    replacement:   '$1'
  - source_labels: ['__meta_consul_tags']
    regex:         ',(production|canary|dev),'
    target_label:  'group'
    replacement:   '$1'
```

**Comment by misterbisson** [comment]
This was solved in https://github.com/autopilotpattern/prometheus/pull/21 and others
